version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: pyspark_db

  pyspark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pyspark
    depends_on:
      - mysql
    volumes:
      - .:/app
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    entrypoint: [ "python", "pyspark_project.py" ]
