# Use the official MySQL image from the Docker Hub
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=rootpasswd
ENV MYSQL_DATABASE=pyspark_db

# Copy the database initialization script
COPY init.sql /docker-entrypoint-initdb.d/